version: 2
updates:
  # Ruby dependencies
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    groups:
      development-tools:
        patterns:
          - "debug"
          - "ruby-lsp*"
          - "rubocop*"
          - "brakeman"
      testing-tools:
        patterns:
          - "rspec*"
          - "capybara"
          - "factory_bot*"
          - "faker"
          - "shoulda-matchers"
          - "lookbook"
          - "simplecov"
      rails-ecosystem:
        patterns:
          - "rails"
          - "turbo-rails"
          - "stimulus-rails"
          - "solid_*"
          - "propshaft"
      deployment-tools:
        patterns:
          - "kamal"
          - "thruster"
          - "puma*"
      google-apis:
        patterns:
          - "google-*"
          - "googleauth"
      background-jobs:
        patterns:
          - "sidekiq"
          - "redis*"
    ignore:
      # Add any dependencies you want to manually control
      # - dependency-name: "rails"
      #   versions: ["7.x", "8.x"]

  # JavaScript dependencies
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    groups:
      javascript-tools:
        patterns:
          - "@hotwired/*"
          - "esbuild*"
          - "tailwindcss*"
          - "daisyui"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
