global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'docker-swarm'
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        role: tasks
    relabel_configs:
      - source_labels: [__meta_docker_service_name]
        target_label: service_name
      - source_labels: [__meta_docker_task_name]
        target_label: task_name
      - source_labels: [__meta_docker_node_name]
        target_label: node_name

  - job_name: 'allspark-instances'
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        role: tasks
    relabel_configs:
      - source_labels: [__meta_docker_service_label_com_docker_stack_namespace]
        regex: 'allspark-.*'
        action: keep
      - source_labels: [__meta_docker_service_name]
        target_label: instance_name
      - source_labels: [__meta_docker_task_name]
        target_label: task_name